[package]
name = "daic_provenance"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "5.2.1", features = ["legacy"] }
serde = { version = "1.0", features = ["derive"] }
